# Site settings
title:       t.reiff
email:       trevorreiff@gmail.com
author:      Trevor Reiff
disqus_shortname: developerquest
description: ""
baseurl:     ""
url:         "http://localhost:4000"
permalink:   "/:categories/:title/"

# Google analytics
google_analytics:   UA-53078606-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
excerpt_separator: ""

# Social icons
show_social_icons: true
github_username:   treiff 
twitter_username:  tlreiff
google_plus_id:    "101280832722709690426"
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
highlighter:  pygments
markdown:     kramdown
permalink:    pretty
sass:
  compressed: true
